ALTER TABLE MATCH DROP CONSTRAINT FK_MATCH_FINALSCORE_ID
ALTER TABLE MATCH DROP CONSTRAINT FK_MATCH_DEFENDER_ID
ALTER TABLE MATCH DROP CONSTRAINT FK_MATCH_CHALLENGER_ID
DROP TABLE COMPETITOR
DROP TABLE MATCHRESULT
DROP TABLE MATCH
DROP TABLE LEAGUE
